NEEDED_COLUMNS: list[str] = [
    "gametype",
    "gid",
    "inning",
    "top_bot",
    "batter",
    "pitcher",
    "outs_pre",
    "outs_post",
    "br1_pre",
    "br2_pre",
    "br3_pre",
    "br1_post",
    "br2_post",
    "br3_post",
    "runs",
    "single",
    "double",
    "triple",
    "hr",
    "sh",
    "hbp",
    "walk",
    "k",
    "xi",
    "roe",
]

OUTPUT_COLUMNS = [
    'gid',
    'batter',
    'pitcher',
    'pa_result',
    'batter_rating_pre',
    'batter_rating_post',
    'pitcher_rating_pre',
    'pitcher_rating_post'
]